POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "test1",
    "email": "test1@gmail.com",
    "password": "1234"
}

##############

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}